const Epub = require("epub-gen");

interface Chapter {
    title: string;
    data: string;
}

export function epub(title: string, coverImage: string, chapters: string[]): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const option = {
            title: title,
            author: "Ari",
            cover: coverImage,
            content: [
                {
                    title: 'Introduction',
                    data: `
                        <h1>Introduction</h1>
                        <p>This book was programmatically generated by Ari...</p>
                    `
                },
                ...chapters.map((chapterText, index): Chapter => ({
                    title: `Chapter ${index + 1}`,
                    data: `<h1>Chapter ${index + 1}</h1>${chapterText}`
                }))
            ],
            appendChapterTitles: false,
        };

        new Epub(option).promise.then((buffer: Buffer) => {
            resolve(buffer);
        }, (err: any) => {
            reject(err);
        });
    });
}