"use client"

// Other imports remain unchanged
import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter, usePathname, useSearchParams } from 'next/navigation'
import styles from '../styles/page.module.css';

export default function Home() {
  const [searchTerm, setSearchTerm] = useState('');
  const router = useRouter();

  // Function to handle the search - update as needed for your project's requirements
  const handleSearch = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && searchTerm) {
      // Navigate to the new page when the search is initiated
      router.push(`/search/${encodeURIComponent(searchTerm)}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>librari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main content area */}
      <main className="flex flex-col items-center justify-center flex-1 px-20 text-center">
        <div className="flex justify-center items-center w-full">
          <input
            type="search"
            placeholder="Search..."
            className="form-input w-full sm:w-3/4 md:w-2/3 lg:w-1/2 rounded-md p-2 text-lg"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onKeyDown={handleSearch}
          />
        </div>
      </main>

      {/* Footer remains unchanged */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}